name: brasov_earth
description: A Flutter example using Maps SDK for Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: 
  bloc: 
  flutter_bloc:
  gem_kit:
    path: plugins/gem_kit
  equatable:
  permission_handler: ^10.4.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/settings.json